### ISSUE TITLE
Fix port open

### ISSUE THREAD

**Issue by Andrey1994** [Mousai-Neurotechnologies/Kinesis#1]
It's not an issue just a suggestion.

This https://github.com/Mousai-Neurotechnologies/Kinesis/blob/ae610c0aa01e5e10932f2877b98e76cf08fffd8b/mneme/utils/realtime_streams.py#L33 can be solved by replacing port /dev/tty...... by /dev/cu.....

For some reason on MacOS /dev/tty hangs while /dev/cu doesnt, its not specific to brainflow

**Comment by garrettmflynn** [comment]
Perfect, thanks Andrey!
